Assay endpoint with aeid=2551 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2642 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2671 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2647 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2645 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2586 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2637 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2572 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2650 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2649 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2678 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2604 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2628 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2608 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2606 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2629 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2595 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2674 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2550 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2612 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

