Assay endpoint with aeid=2583 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2587 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2580 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2652 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2570 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2567 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2684 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2632 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2626 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2683 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2616 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2651 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2593 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2585 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2676 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2679 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2685 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

Assay endpoint with aeid=2639 failed: cannot set a frame with no defined index and a scalar
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 189, in process
    df_no_fit.loc[:, 'fit_params'] = None
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 849, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1751, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

